### ISSUE TITLE
Help with 256_tets.npz

### ISSUE THREAD

**Issue by BrandonHanx** [ashawkey/fantasia3d.unofficial#3]
Hi @ashawkey 

Thanks for your quick implementation!

Could you please share the 256_tets.npz file? 
I tried to generate it by myself but always got a segmentation fault.

**Comment by ashawkey** [comment]
@BrandonHanx Hi, here you go: https://drive.google.com/file/d/1lgvEKNdsbW5RS4gVxJbgBS4Ac92moGSa/view?usp=sharing

**Comment by BrandonHanx** [comment]
Many thanks!
