### ISSUE TITLE
About the quality

### ISSUE THREAD

**Issue by garychan22** [ashawkey/fantasia3d.unofficial#7]
Thanks for your great repo!

I have tried this repo and the shape is well learnt, while the texture is not satisfactory, e.g. the ripe strawberry looks green. I am curious that is this method also about luck? Or something I have not set right?

**Comment by ashawkey** [comment]
@garychan22 Hi, I guess you can try longer epochs? Or you can wait for the official release.

**Comment by chengyuhangg** [comment]
Hi, you can try
"FLAGS.directional_text=True"
although the author mentions that it is not added when generating objects without directionality

**Comment by garychan22** [comment]
@ashawkey i have tried larger epochs and the texture is better learnt but still looks far from the example provided in this repo.

@ChengYuhang99 thanks for your valuable suggestion! now the learnt textures are more like the examples provided in this repo!
